package uni.advanced_programming;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * ConcreteOutputStrategy is a class that implements the AbstractOutputStrategy interface.
 * Following the Strategy Pattern Framework design, it is used to make concrete the abstract strategy defined by the
 * framework. In this version, it takes a path to the count_anagram.txt and writes this file with the results of the pipeline.
 */
public class ConcreteOutputStrategy implements AbstractOutputStrategy<String,String>{
    private final Path outputFile;

    public ConcreteOutputStrategy(String fileName) {
        this.outputFile = Path.of(fileName);
    }

    /**
     * Implementation of output method, in which it takes the words from the data generated by the collect stage
     * of the pipeline and prints the pair (ciao(word), word) in the output file.
     * @param data results of collect stage of the pipeline
     */
    @Override
    public void output(Stream<Pair<String, List<String>>> data) {
        // Transform to "key -> count" lines
        List<String> lines = data
                .map(pair -> pair.getKey() + " -> " + pair.getValue().size())
                .collect(Collectors.toList());

        try {
            Files.write(outputFile, lines);
            System.out.println("Results written to " + outputFile.toAbsolutePath());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
